language: scala
scala:
   - 2.12.4

jdk:
   - oraclejdk8

# We cannot use the container based env because Cassandra isn't supported there
sudo: false

# Use a recent Cassandra version
#before_install:
#  - sudo rm -rf /var/lib/cassandra/*
#  - mkdir -p /opt/cassandra
#  - wget -P /opt/cassandra http://www.us.apache.org/dist/cassandra/3.11.2/apache-cassandra-3.11.2-bin.tar.gz && tar -xvzf /opt/cassandra/apache-cassandra-3.11.2-bin.tar.gz && sh /opt/cassandra/apache-cassandra-3.11.2/bin/cassandra

before_script:
  - mkdir $TRAVIS_BUILD_DIR/tmp
  - export SBT_OPTS="-Djava.io.tmpdir=$TRAVIS_BUILD_DIR/tmp"
  - export EMBEDDED_CASSANDRA=true

script:
  - sbt +test +publish

# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
#    - /opt/cassandra

# Cleanup the cached directories to avoid unnecessary cache updates
before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete
