language: scala
scala:
   - 2.12.4

jdk:
   - oraclejdk8

# We cannot use the container based env because docker isn't supported there
sudo: required

services:
- docker

# Start Cassandra in a docker image
before_install:
 - docker pull cassandra:3
 - docker run -d -p 7199:7199 -p 9042:9042 -p 9160:9160 -e CASSANDRA_DC=DC1 -e CASSANDRA_START_RPC=true  -e CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch cassandra:3

before_script:
  - mkdir $TRAVIS_BUILD_DIR/tmp
  - export SBT_OPTS="-Djava.io.tmpdir=$TRAVIS_BUILD_DIR/tmp"

script:
  - sbt +test +publish

# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

# Cleanup the cached directories to avoid unnecessary cache updates
before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete
